# Generated by Django 6.0.4 on 2026-04-28 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_readingsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='end_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='start_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Career', 'Career-Specific Reading'), ('Self-Dev', 'Self-Development Reading')], max_length=20)),
                ('status', models.CharField(choices=[('Reading', 'Currently Reading'), ('Completed', 'Completed'), ('ToRead', 'To Read')], default='ToRead', max_length=20)),
                ('current_page', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('cover_image', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='readingsession',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='tracker.book'),
        ),
    ]
