# Generated by Django 6.0.4 on 2026-04-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_readingsession_end_page_readingsession_start_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='last_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='total_paused_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
