# Generated by Django 6.0.4 on 2026-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_readingsession_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
